//==========================================================================
//==               Copyright (c) 2024 Synopsys, Inc.
//==     All Rights reserved - Unpublished - rights reserved under
//==     the Copyright laws of the United States of America.
//== 
//== U.S. Patents: 7,093,156 B1 and 7,406,620 B2 (and more pending).
//== 
//== This file includes the Confidential information of Synopsys, Inc.
//== and GLOBALFOUNDRIES.
//== The receiver of this Confidential Information shall not disclose
//== it to any third party and shall protect its confidentiality by
//== using the same degree of care, but not less than a reasonable
//== degree of care, as the receiver uses to protect receiver's own
//== Confidential Information.
//== Licensee acknowledges and agrees that all output generated for
//== Licensee by Synopsys, Inc. as described in the pertinent Program
//== Schedule(s), or generated by Licensee through use of any Compiler
//== licensed hereunder contains information that complies with the
//== Virtual Component Identification Physical Tagging Standard (VCID)
//== as maintained by the Virtual Socket Interface Alliance (VSIA).
//== Such information may be expressed in GDSII Layer 63 or other such
//== layer designated by the VSIA, hardware definition languages, or
//== other formats. Licensee is not authorized to alter or change any
//== such information.
//==========================================================================
//== Generated: 05/23/2024 02:45:13
//== Synopsys Memory Release: V04R30SZ_21JUN2020
//== 22fdsoi PDK 22FDX_V1.3_3.0
//==
//== IDTK_ROOT: /ux/lib9/reltp/Library/Synopsys/GF_22FDX/MC/IN22FDX_MEMR2PV_COMPILER_FDK_RELV04R30SZ_21JUN2020/idtk
//== IDDK_ROOT: /ux/lib9/reltp/Library/Synopsys/GF_22FDX/MC/IN22FDX_MEMR2PV_COMPILER_FDK_RELV04R30SZ_21JUN2020/iddk
//== IDDK_TECH: 22fdsoi
//==========================================================================

//==========================================================================
//==               Copyright (c) 2024 Synopsys, Inc.
//==     All Rights reserved - Unpublished - rights reserved under
//==     the Copyright laws of the United States of America.
//== 
//== U.S. Patents: 7,093,156 B1 and 7,406,620 B2 (and more pending).
//== 
//== This file includes the Confidential information of Synopsys, Inc.
//== and GLOBALFOUNDRIES.
//== The receiver of this Confidential Information shall not disclose
//== it to any third party and shall protect its confidentiality by
//== using the same degree of care, but not less than a reasonable
//== degree of care, as the receiver uses to protect receiver's own
//== Confidential Information.
//== Licensee acknowledges and agrees that all output generated for
//== Licensee by Synopsys, Inc. as described in the pertinent Program
//== Schedule(s), or generated by Licensee through use of any Compiler
//== licensed hereunder contains information that complies with the
//== Virtual Component Identification Physical Tagging Standard (VCID)
//== as maintained by the Virtual Socket Interface Alliance (VSIA).
//== Such information may be expressed in GDSII Layer 63 or other such
//== layer designated by the VSIA, hardware definition languages, or
//== other formats. Licensee is not authorized to alter or change any
//== such information.
//==========================================================================
//== Generated: 05/23/2024 02:45:13
//== Synopsys Memory Release: V04R30SZ_21JUN2020
//== 22fdsoi PDK 22FDX_V1.3_3.0
//==
//== IDTK_ROOT: /ux/lib9/reltp/Library/Synopsys/GF_22FDX/MC/IN22FDX_MEMR2PV_COMPILER_FDK_RELV04R30SZ_21JUN2020/idtk
//== IDDK_ROOT: /ux/lib9/reltp/Library/Synopsys/GF_22FDX/MC/IN22FDX_MEMR2PV_COMPILER_FDK_RELV04R30SZ_21JUN2020/iddk
//== IDDK_TECH: 22fdsoi
//==========================================================================

`timescale 1ns / 1ps
module MBH_ZSWL_IN22FDX_R2PV_WFVG_W00128B128M02C128
   (
    input  clkA,
    input  clkB,
    input  cenA,
    input  cenB,
    input  deepsleep,
    input  powergate,
    input  [6+1-1:0] aA,
    input  [6+1-1:0] aB,
    input  [128-1:0] d,
    input  [128-1:0] bw,
    output [128-1:0] q
    );

// VSIA_Soft_IP_Tag % Vendor SYNOPSYS % Product 22FDX % Version v00r50 % Metric 100 % IP_Owner VTMDC % Celltype IP % Cell_Id MBH_ZSWL_IN22FDX_R2PV_WFVG_W00128B128M02C128 % Signature 100 % Tag_Spec 3.0 % Date_Time 20240523 % Process_Step Source

   wire [6-1:0] n_rwfa = {6{1'b0}};
   wire [128-1:0]    n_obsv_dbw;
   wire                    n_obsv_ctlA;
   wire                    n_obsv_ctlB;
   MBH_MSWL_IN22FDX_R2PV_WFVG_W00128B128M02C128 MBH0
     (
      .CLK_A       (clkA),
      .CLK_B       (clkB),
      .CEN_A       (cenA),
      .CEN_B       (cenB),
      .DEEPSLEEP   (deepsleep),
      .POWERGATE   (powergate),
      .aA          (aA),
      .aB          (aB),
      .D           (d),
      .BW          (bw),
      .T_LOGIC     (1'b0),
      .MA_SAWL     (1'b0),
      .MA_WL       (1'b0),
      .MA_WRAS     (1'b0),
      .MA_WRASD    (1'b0),
      .MA_TPA      (1'b0),
      .MA_TPB      (1'b0),
      .RWE         (1'b0),
      .RWFA        (n_rwfa),
      .Q           (q),
      .OBSV_DBW    (n_obsv_dbw),
      .OBSV_CTL_A  (n_obsv_ctlA),
      .OBSV_CTL_B  (n_obsv_ctlB)
      );
endmodule